dataset:
  data: /data/raw/02_medical_records.csv

features:
  drop_features: []
  numeric_features:
    ["age", "resting_BP", "cholesterol", "fasting_BS", "max_HR", "old_peak"]
  categorical_features:
    ["gender", "chest_pain", "resting_ECG", "exercise_angina", "ST_slope"]
  ordinal_features: { "gender": ["F", "M"], "exercise_angina": ["No", "Yes"] }
  target_features: "cv_issue"

setup:
  train_size: 0.8
  test_size: 0.2
  memory: "None"
